version: '3'

services: 
    web:
        image: nginx:latest
        container_name: hello-web
        ports: 
            - 8088:80
        volumes: 
            - ./code:/var/www/html
            - ./virtual.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - app-network
    php:
        image: php:7.4-fpm
        container_name: hello-php
        volumes: 
            - ./code:/var/www/html
        networks: 
            - app-network
        
networks: 
    app-network:
        driver: bridge

